[workspace]
authors = ["Andrei-Vlad Badelita <vladb@cantab.net>"]
channels = ["conda-forge", "bioconda"]
name = "msa-transformer"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]


[tasks]

[dependencies]
pytorch = ">=2.8.0,<3"
cudatoolkit = ">=11.8.0,<12"
ipython = ">=9.6.0,<10"
cython = ">=3.1.4,<4"
pytorch-lightning = ">=2.5.5,<3"
numpy = ">=2.3.3,<3"
hydra-core = ">=1.3.2,<2"
scikit-learn = ">=1.7.2,<2"

[pypi-dependencies]
evo = { git = "https://github.com/vbadelita/evo.git", branch = "main" }